project:
  type: website
  output-dir: docs

website:
  title: "RoseHoover.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me!
      - href: test.qmd
        text: Stat244

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

